// Code generated by testgen/constgen.py; DO NOT EDIT.
package fixedPoint

// Exported scale constants
const Fix64Scale = 1E+8
const Fix64One = Fix64(1 * Fix64Scale) // 1 in fix64
const Fix128Scale = 1E+24 // NOTE: Bigger than uint64! Mostly here as documentation...
var Fix128One = Fix128(raw128{0x000000000000d3c2, 0x1bcecceda1000000})

// Internal scale constants
const extraBits = 8 // Number of extra bits for fix64_extra and fix128_extra
const fix64ExtraScale = Fix64Scale << extraBits // 2.56E+10
const fix128ExtraScale = 2.56E+26 // NOTE: Bigger than uint64! Mostly here as documentation...

// Fix64 transcendental constants
const Fix64_Pi = Fix64(0x12b9b0a1)
const fix64_2Pi = Fix64(0x25736143)
const fix64_PiOver2 = Fix64(0x95cd851)
const fix64_3PiOver2 = Fix64(0x1c1688f2)
const fix64_TwoPiShifted33 = uint64(0x4ae6c2856f98469f)

// Fix128 transcendental constants
var Fix128_Pi = Fix128(raw128{0x0000000000029942, 0x1439a0abd72cb0b3})
var fix128_2Pi = Fix128(raw128{0x0000000000053284, 0x28734157ae596167})
var fix128_PiOver2 = Fix128(raw128{0x0000000000014ca1, 0x0a1cd055eb96585a})
var fix128_3PiOver2 = Fix128(raw128{0x000000000003e5e3, 0x1e567101c2c3090d})
var fix128_TwoPiShifted44 = raw128(raw128{0x5328428734157ae5, 0x96166c43d36043ac})

// fix64_extra transcendental constants
const fix64_extra_Pi = fix64_extra(0x12b9b0a15c)
const fix64_extra_2Pi = fix64_extra(0x25736142b8)
const fix64_extra_PiOver2 = fix64_extra(0x95cd850ae)
const fix64_extra_3PiOver2 = fix64_extra(0x1c1688f20a)
const fix64_extra_sinIota = fix64_extra(0xf0d74d)

// ln(2) for fix64_extra
const ln2_fix64_extra = int64(0x421a89e0e)
