[project]
name = "testgen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mpmath>=1.3.0",
    "numba>=0.61.2",
    "pipe>=2.2",
]
