# fix64_testgen.py
# Code generator for Go test data arrays for UFix64 and Fix64 arithmetic

from add64 import generate_add_ufix64_tests, generate_add_ufix64_overflow_tests, generate_add_fix64_tests, generate_add_fix64_overflow_tests, generate_add_fix64_neg_overflow_tests
from sub64 import generate_sub_ufix64_tests, generate_sub_ufix64_neg_overflow_tests, generate_sub_fix64_tests, generate_sub_fix64_overflow_tests, generate_sub_fix64_neg_overflow_tests
from mul64 import generate_mul_ufix64_tests, generate_mul_ufix64_overflow_tests, generate_mul_fix64_tests, generate_mul_fix64_overflow_tests
from div64 import generate_div_ufix64_tests, generate_div_ufix64_overflow_tests, generate_div_ufix64_divbyzero_tests, generate_div_fix64_tests, generate_div_fix64_overflow_tests, generate_div_fix64_divbyzero_tests

def main():
    go_lines = [
        "// Code generated by testgen/fix64_testgen.py; DO NOT EDIT.",
        "package fixedPoint",
        "",
    ]
    go_lines.extend(generate_add_ufix64_tests())
    go_lines.extend(generate_add_ufix64_overflow_tests())
    go_lines.extend(generate_add_fix64_tests())
    go_lines.extend(generate_add_fix64_overflow_tests())
    go_lines.extend(generate_add_fix64_neg_overflow_tests())
    go_lines.extend(generate_sub_ufix64_tests())
    go_lines.extend(generate_sub_ufix64_neg_overflow_tests())
    go_lines.extend(generate_sub_fix64_tests())
    go_lines.extend(generate_sub_fix64_overflow_tests())
    go_lines.extend(generate_sub_fix64_neg_overflow_tests())
    go_lines.extend(generate_mul_ufix64_tests())
    go_lines.extend(generate_mul_ufix64_overflow_tests())
    go_lines.extend(generate_mul_fix64_tests())
    go_lines.extend(generate_mul_fix64_overflow_tests())
    go_lines.extend(generate_div_ufix64_tests())
    go_lines.extend(generate_div_ufix64_overflow_tests())
    go_lines.extend(generate_div_ufix64_divbyzero_tests())
    go_lines.extend(generate_div_fix64_tests())
    go_lines.extend(generate_div_fix64_overflow_tests())
    go_lines.extend(generate_div_fix64_divbyzero_tests())
    print('\n'.join(go_lines))

if __name__ == "__main__":
    main()
