# fix64_testgen.py
# Code generator for Go test data arrays for UFix64 and Fix64 arithmetic

from add64 import *
from sub64 import *
from mul64 import *
from div64 import *
from trans64 import *
from decimal import getcontext

def main():
    getcontext().prec = 100  # Set precision for Decimal operations
    go_lines = [
        "// Code generated by testgen/fix64_testgen.py; DO NOT EDIT.",
        "package fixedPoint",
        "",
    ]
    go_lines.extend(generate_add_ufix64_tests())
    go_lines.extend(generate_add_ufix64_overflow_tests())
    go_lines.extend(generate_add_fix64_tests())
    go_lines.extend(generate_add_fix64_overflow_tests())
    go_lines.extend(generate_add_fix64_neg_overflow_tests())
    go_lines.extend(generate_sub_ufix64_tests())
    go_lines.extend(generate_sub_ufix64_neg_overflow_tests())
    go_lines.extend(generate_sub_fix64_tests())
    go_lines.extend(generate_sub_fix64_overflow_tests())
    go_lines.extend(generate_sub_fix64_neg_overflow_tests())
    go_lines.extend(generate_mul_ufix64_tests())
    go_lines.extend(generate_mul_ufix64_overflow_tests())
    go_lines.extend(generate_mul_ufix64_underflow_tests())
    go_lines.extend(generate_mul_fix64_tests())
    go_lines.extend(generate_mul_fix64_overflow_tests())
    go_lines.extend(generate_mul_fix64_underflow_tests())
    go_lines.extend(generate_mul_fix64_neg_overflow_tests())
    go_lines.extend(generate_div_ufix64_tests())
    go_lines.extend(generate_div_ufix64_overflow_tests())
    go_lines.extend(generate_div_ufix64_underflow_tests())
    go_lines.extend(generate_div_ufix64_divbyzero_tests())
    go_lines.extend(generate_div_fix64_tests())
    go_lines.extend(generate_div_fix64_overflow_tests())
    go_lines.extend(generate_div_fix64_neg_overflow_tests())
    go_lines.extend(generate_div_fix64_underflow_tests())
    go_lines.extend(generate_div_fix64_divbyzero_tests())
    go_lines.extend(generate_sqrt_ufix64_tests())
    go_lines.extend(generate_ln_ufix64_tests())
    print('\n'.join(go_lines))

if __name__ == "__main__":
    main()
